
export const translations = {
  en: {
    send: 'Send',
    placeholder: 'Type your message here... (Shift + Enter for new line)',
    stopGenerating: 'Stop Generating',
    switchToChatMode: 'Switch to Chat Mode',
    switchToWriteMode: 'Switch to Write Mode',
    switchToRuleMode: 'Switch to Rule Mode',
    maximizeInput: 'Maximize Input Area',
    minimizeInput: 'Minimize Input Area',
    buildIndexAndAsk: 'Build Index & Ask',
    soundOn: 'Sound On',
    soundOff: 'Sound Off',
    stepByStepMode: 'Step By Step Mode',
  },
  zh: {
    send: '发送',
    placeholder: '在此输入你的消息... (Shift + Enter 换行)',
    stopGenerating: '停止生成',
    switchToChatMode: '切换到对话模式',
    switchToWriteMode: '切换到写作模式',
    switchToRuleMode: '切换到规则模式',
    maximizeInput: '最大化输入区',
    minimizeInput: '最小化输入区',
    buildIndexAndAsk: '构建索引并提问',
    soundOn: '声音：开',
    soundOff: '声音：关',
    stepByStepMode: '逐步模式',
  },
};
